name: Test if the program compiles correctly

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run CMake
      run: cmake .

    - name: Run Makefile
      run: make
